site_name: Special Happiness Software Development Standards
site_url: https://geoff1900.github.io/
repo_url: https://github.com/Geoff1900/special-happiness
docs_dir: docs
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: custom
  features:
    - navigation.tabs
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.code.copy
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to optimise site functionality and give you the best
      possible experience, recognise your repeated visits and preferences, as
      well as to measure the effectiveness of our site and whether
      users find what they're searching for. With your consent, you're helping
      us to make our site better.
    cookies:
      analytics:
        name: Simple Analytics
        checked: true
  analytics:
    provider: simple
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
plugins:
  - search
  - table-reader
  - awesome-nav
